// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scullery.EntityFrameworkCore;

namespace Scullery.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(SculleryContext))]
    [Migration("20181011024736_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Scullery.EntityFrameworkCore.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Arguments");

                    b.Property<bool>("IsStatic");

                    b.Property<string>("Method");

                    b.Property<string>("Name");

                    b.Property<string>("Parameters");

                    b.Property<string>("Returns");

                    b.Property<DateTime?>("Scheduled");

                    b.Property<int>("Status");

                    b.Property<string>("TimeZone");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
